from . import res_users
from . import res_partner
from . import sale_order
from . import product_template
from . import product_favorite
from . import delivery_zone
from . import rate_limit
from . import timeslot_capacity
from . import pin_reset_wizard
from . import batch_picking_wizard
from . import batch_picking_settings_wizard
